# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for starship to execute command (ms)
command_timeout = 1000

[aws]
disabled = true

[buf]
symbol = 'ï’ '

[c]
symbol = 'î˜ '

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ—](bold red)'

[docker_context]
symbol = 'ïŒˆ '
only_with_files = true

[git_branch]
symbol = 'ï˜ '

[golang]
symbol = 'î˜§ '

[hostname]
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
ssh_only = true

[lua]
symbol = 'î˜  '

[memory_usage]
symbol = 'ï¡š '

[os]
disabled = false

[os.symbols]
Alpine = 'ïŒ€ '
Arch = 'ïŒƒ '
Debian = 'ïŒ† '
Fedora = 'ïŒŠ '
Linux = 'ïŒš '
Macos = 'ïŒ‚ '

[python]
symbol = 'îˆµ '

[status]
disabled = false
style = 'red'
symbol = 'î€ '
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'ï™ '
sigint_symbol = 'î€ '
signal_symbol = 'î€ '
format = '[\[ $symbol$common_meaning$signal_name$maybe_int \]]($style) '
map_symbol = true
